---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hkksh4mguhpynaew/public_html/
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp asset-manifest.json $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp logo192.png $DEPLOYPATH
    - /bin/cp logo512.png $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH